### ISSUE TITLE
Please add flux.early_stopping example in Readme

### ISSUE THREAD

**Issue by rcherukuri12** [jondeuce/Ignite.jl#2]
Delightful pkg to use.
Please add example to show how function call flux.early_stopping(..)  can be added to training.

**Comment by jondeuce** [comment]
Glad you like it! Thanks for the suggestion, that's a good idea. Let me think about the best way to do it, and I'll add an example to the README.

Roughly, you probably want to add an event which is triggered after each evaluation run that sets `trainer.should_terminate = Flux.early_stopping(...)`. This will stop training when the early stopping condition returns `true`.

**Comment by jondeuce** [comment]
README is updated with an example. I'll close this issue now, but feel free to followup if you need.
